using System.Text.Json.Serialization;
using Microsoft.CodeAnalysis;
using RoslynMCP.Services;
using RoslynMCP.Services.ExternalSource;

namespace RoslynMCP.Lsp.Handlers;

public sealed record VirtualDocumentParams(
    [property: JsonPropertyName("uri")] string Uri);

/// <summary>Text for a document with no file behind it, plus what to tell the reader it is.</summary>
public sealed record VirtualDocumentResult(
    [property: JsonPropertyName("text")] string Text,
    [property: JsonPropertyName("description")] string Description,
    [property: JsonPropertyName("languageId")] string LanguageId = "csharp");

/// <summary>
/// Serves documents the compiler knows about but the file system does not: source-generated
/// files, and decompiled metadata.
/// </summary>
/// <remarks>
/// One resolver for both schemes, so the client registers a single content provider:
/// <c>roslynsense-generated:/{projectPath}/{hintName}</c> and
/// <c>roslynsense-metadata:/{assemblyPath}/{typeName}</c>.
///
/// Generated documents genuinely have no path — a generator's output exists only inside the
/// compilation, so opening one any other way means writing a copy that immediately goes stale.
/// Decompiled sources do get written to disk, and stay that way: a real file keeps hover,
/// go-to-definition, and find-references working inside it, which a virtual buffer would not.
/// This scheme exists for them so the reader can open a type from an assembly on demand.
/// </remarks>
internal static class VirtualDocumentHandler
{
    public const string GeneratedScheme = "roslynsense-generated";
    public const string MetadataScheme = "roslynsense-metadata";

    public static async Task<VirtualDocumentResult?> ResolveAsync(
        VirtualDocumentParams p, CancellationToken ct)
    {
        if (!TryParse(p.Uri, out string scheme, out string first, out string second))
            return null;

        return scheme switch
        {
            GeneratedScheme => await GeneratedAsync(first, second, ct),
            MetadataScheme => await MetadataAsync(first, second, ct),
            _ => null,
        };
    }

    /// <summary>The generated documents of one project, as URIs the client can open.</summary>
    public static async Task<GeneratedFileInfo[]> ListGeneratedAsync(string projectPath, CancellationToken ct)
    {
        try
        {
            var (_, project) = await WorkspaceService.GetOrOpenProjectAsync(projectPath, cancellationToken: ct);
            var documents = await project.GetSourceGeneratedDocumentsAsync(ct);

            // Listing them in the tree is the cheapest moment to learn their URIs, so a later
            // "find all references" that lands in generated code already knows where to point.
            GeneratedDocumentRegistry.Register(projectPath, documents);

            return documents
                .Select(document => new GeneratedFileInfo(
                    HintName(document),
                    GeneratorOf(document),
                    UriFor(GeneratedScheme, projectPath, HintName(document))))
                .OrderBy(f => f.Generator, StringComparer.OrdinalIgnoreCase)
                .ThenBy(f => f.HintName, StringComparer.OrdinalIgnoreCase)
                .ToArray();
        }
        catch (Exception ex)
        {
            ServiceLog.Warn(
                $"Could not list generated files for '{Path.GetFileName(projectPath)}': {ex.Message}",
                key: $"generated-list:{projectPath}");
            return [];
        }
    }

    private static async Task<VirtualDocumentResult?> GeneratedAsync(
        string projectPath, string hintName, CancellationToken ct)
    {
        var (_, project) = await WorkspaceService.GetOrOpenProjectAsync(projectPath, cancellationToken: ct);
        var documents = await project.GetSourceGeneratedDocumentsAsync(ct);

        var match = documents.FirstOrDefault(d =>
            HintName(d).Equals(hintName, StringComparison.OrdinalIgnoreCase));
        if (match is null)
            return null;

        var text = await match.GetTextAsync(ct);
        return new VirtualDocumentResult(
            text.ToString(),
            $"Generated by {GeneratorOf(match)} — read-only");
    }

    private static async Task<VirtualDocumentResult?> MetadataAsync(
        string assemblyPath, string typeName, CancellationToken ct)
    {
        // The same resolution the search panel and F12 use, so the three provably agree about
        // what "the source of this type" is rather than happening to agree.
        var external = await ExternalSourceService.TryResolveTypeAsync(assemblyPath, typeName, ct);
        if (external is null)
            return null;

        string text;
        try
        {
            text = await File.ReadAllTextAsync(external.FilePath, ct);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            return null;
        }

        return new VirtualDocumentResult(
            text,
            $"{external.Title} for {Path.GetFileName(assemblyPath)} — {external.Provenance}, read-only");
    }

    public static string UriFor(string scheme, string owner, string name) =>
        // The owner is a path with separators and a drive letter, so it goes in the query rather
        // than the path, where the client's URI parser would rewrite it.
        $"{scheme}:/{Uri.EscapeDataString(name)}?{Uri.EscapeDataString(owner)}";

    public static bool TryParseUri(string uri, out string scheme, out string owner, out string name) =>
        TryParse(uri, out scheme, out owner, out name);

    private static bool TryParse(string uri, out string scheme, out string owner, out string name)
    {
        scheme = owner = name = "";

        int schemeEnd = uri.IndexOf(":/", StringComparison.Ordinal);
        int queryStart = uri.IndexOf('?', StringComparison.Ordinal);
        if (schemeEnd < 0 || queryStart < schemeEnd)
            return false;

        scheme = uri[..schemeEnd];
        name = Uri.UnescapeDataString(uri[(schemeEnd + 2)..queryStart]);
        owner = Uri.UnescapeDataString(uri[(queryStart + 1)..]);
        return name.Length > 0 && owner.Length > 0;
    }

    private static string HintName(SourceGeneratedDocument document) =>
        document.HintName is { Length: > 0 } hint ? hint : document.Name;

    /// <summary>
    /// The generator that produced a document. Its identity is in the path Roslyn synthesizes,
    /// which is <c>{generator assembly}\{generator type}\{hint name}</c>.
    /// </summary>
    private static string GeneratorOf(SourceGeneratedDocument document)
    {
        string[] parts = (document.FilePath ?? "").Split(
            ['\\', '/'], StringSplitOptions.RemoveEmptyEntries);

        return parts.Length >= 2 ? parts[^2] : "a source generator";
    }
}

public sealed record GeneratedFileInfo(
    [property: JsonPropertyName("hintName")] string HintName,
    [property: JsonPropertyName("generator")] string Generator,
    [property: JsonPropertyName("uri")] string Uri);
