import * as assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import type * as vscode from 'vscode';
import type { LanguageClient } from 'vscode-languageclient/node';
import { loadWithMocks } from './mockModule';

function uri(scheme: string, path = '/Generator/Example.g.cs'): vscode.Uri {
    return { scheme, path, toString: () => `${scheme}:${path}` } as vscode.Uri;
}

function setup() {
    let save!: () => void;
    let open!: (value: string | vscode.Uri) => Promise<void>;
    const providers = new Map<string, vscode.TextDocumentContentProvider>();
    const refreshed: vscode.Uri[] = [];
    const requests: { method: string; uri: string; token: vscode.CancellationToken }[] = [];
    const shown: { document: unknown; preview: boolean }[] = [];
    const languages: { document: unknown; language: string }[] = [];
    const statuses: string[] = [];
    const documents: { uri: vscode.Uri }[] = [];
    const token = { isCancellationRequested: false } as vscode.CancellationToken;
    const state = {
        connected: true,
        error: undefined as Error | undefined,
        response: { text: '\uFEFF// generated\r\nclass Example { }\r\n', description: 'Generated by ExampleGenerator',
            languageId: 'csharp' } as { text: string; description: string; languageId: string } | null,
    };
    const client = {
        sendRequest: async (method: string, params: { uri: string }, cancellation: vscode.CancellationToken) => {
            requests.push({ method, uri: params.uri, token: cancellation });
            if (state.error) { throw state.error; }
            return state.response;
        },
    };
    const module = loadWithMocks<typeof import('../virtualDocuments')>(require.resolve('../virtualDocuments'), {
        vscode: {
            EventEmitter: class {
                readonly event = () => ({ dispose() {} });
                fire(value: vscode.Uri) { refreshed.push(value); }
                dispose() {}
            },
            Uri: { parse: (value: string) => {
                const separator = value.indexOf(':');
                return uri(value.slice(0, separator), value.slice(separator + 1));
            } },
            workspace: {
                textDocuments: documents,
                registerTextDocumentContentProvider: (scheme: string, provider: vscode.TextDocumentContentProvider) => {
                    providers.set(scheme, provider);
                    return { dispose() {} };
                },
                openTextDocument: async (value: vscode.Uri) => ({ uri: value,
                    text: await providers.get(value.scheme)!.provideTextDocumentContent(value, token) }),
                onDidSaveTextDocument: (callback: typeof save) => { save = callback; },
            },
            commands: { registerCommand: (_name: string, callback: typeof open) => { open = callback; } },
            languages: { setTextDocumentLanguage: async (document: unknown, language: string) => {
                languages.push({ document, language });
                return document;
            } },
            window: {
                showTextDocument: async (document: unknown, options: { preview: boolean }) => {
                    shown.push({ document, preview: options.preview });
                },
                setStatusBarMessage: (message: string) => { statuses.push(message); },
            },
        },
    });
    module.registerVirtualDocuments({ subscriptions: [] } as unknown as vscode.ExtensionContext,
        () => state.connected ? client as unknown as LanguageClient : undefined);
    return { state, providers, refreshed, requests, shown, languages, statuses, documents, token, save, open,
        content: async (value: vscode.Uri) => await providers.get(value.scheme)!.provideTextDocumentContent(value, token) };
}

describe('virtual documents', () => {
    it('preserves generated text exactly for server positions while giving metadata its banner', async () => {
        const state = setup();
        const generated = uri('roslynsense-generated');
        const metadata = uri('roslynsense-metadata', '/Library/Example.cs');

        assert.equal(await state.content(generated), state.state.response!.text);
        assert.equal(await state.content(metadata),
            `// ${state.state.response!.description}\n\n${state.state.response!.text}`);
        assert.equal(state.requests.length, 2);
        assert.equal(state.requests[0].method, 'roslynSense/virtualDocument');
        assert.equal(state.requests[0].uri, generated.toString());
        assert.equal(state.requests[0].token, state.token);
    });

    it('refreshes every open generated document on save and fetches its new content', async () => {
        const state = setup();
        const first = uri('roslynsense-generated');
        const second = uri('roslynsense-generated', '/Generator/Other.g.cs');
        state.documents.push({ uri: first }, { uri: uri('file', '/Example.cs') },
            { uri: uri('roslynsense-metadata') }, { uri: second });
        await state.content(first);
        state.state.response!.text = 'class Updated { }\n';

        state.save();

        assert.deepEqual(state.refreshed, [first, second]);
        assert.equal(await state.content(first), 'class Updated { }\n');
        assert.equal(state.requests.length, 2);
    });

    it('opens generated source as C# and shows its description outside the source text', async () => {
        const state = setup();
        const generated = uri('roslynsense-generated');
        await state.open(generated.toString());

        assert.equal(state.shown.length, 1);
        assert.equal(state.shown[0].preview, true);
        assert.equal((state.shown[0].document as { text: string }).text, state.state.response!.text);
        assert.equal(state.languages[0].document, state.shown[0].document);
        assert.equal(state.languages[0].language, 'csharp');
        assert.deepEqual(state.statuses, [state.state.response!.description]);
    });

    it('returns readable fallback content when the server is absent or a generated file is gone', async () => {
        const state = setup();
        const generated = uri('roslynsense-generated');
        state.state.connected = false;
        assert.match((await state.content(generated))!, /server is not running/);
        assert.equal(state.requests.length, 0);

        state.state.connected = true;
        state.state.response = null;
        const missing = await state.content(generated);
        assert.ok(missing?.includes(generated.path));
        assert.match(missing!, /generator may no longer produce it/);
    });

    it('contains request failures instead of rejecting document opening', async () => {
        const state = setup();
        state.state.error = new Error('connection closed');

        const content = await state.content(uri('roslynsense-generated'));

        assert.match(content!, /Could not load .*connection closed/);
    });
});
