namespace RoslynMCP.Services;

/// <summary>
/// A throwaway <c>.sln</c> listing an arbitrary subset of a real solution's projects, so Roslyn can
/// be asked to load exactly that subset in a single batch.
/// </summary>
/// <remarks>
/// <para>
/// Roslyn's MSBuild loader has two shapes and no third: <c>OpenProjectAsync</c>, which loads one
/// project and its transitive <c>ProjectReference</c> closure, and <c>OpenSolutionAsync</c>, which
/// loads everything a <c>.sln</c> lists. Both build a fresh <c>BuildHostProcessManager</c> — a
/// <c>dotnet</c> subprocess, a cold MSBuild <c>ProjectCollection</c> and a full re-parse of the SDK
/// targets — and dispose it when the call returns, so the cost is per <em>call</em>, not per
/// project. Measured on a generated 34-project solution: about 1.6 s of fixed cost per call, then
/// roughly 330 ms for each project inside it.
/// </para>
/// <para>
/// That is what makes loading nine projects one at a time cost 14.3 s while loading the same nine
/// in one batch costs 3.7 s, and it is why this type exists. Neither built-in shape fits "load
/// these nine": <c>OpenProjectAsync</c> nine times pays the fixed cost nine times, and
/// <c>OpenSolutionAsync</c> over the real solution pays it once but then loads all thirty-four
/// (12.3 s, and twenty-five projects of retained memory nobody asked for). Writing a solution file
/// that lists exactly the wanted subset gets the batch discount without the batch.
/// </para>
/// <para>
/// Written to a temp directory rather than beside the real solution: a file appearing inside the
/// user's repository shows up in <c>git status</c>, and the extension watches
/// <c>**/*.{sln,slnx}</c> — so creating one there would fire a solution-changed event and evict the
/// very workspace this is loading. The solution-relative MSBuild properties that a temp location
/// would otherwise break are supplied explicitly by <see cref="GlobalProperties"/> instead, which
/// is what MSBuild itself does when it builds a solution.
/// </para>
/// <para>
/// Deliberately minimal: project lines and nothing else. Roslyn's loader reads only the project
/// paths out of a solution file — <c>SolutionFile.Parse</c> feeds <c>AbsolutePath</c> into the
/// loader and never looks at the configuration blocks — so emitting
/// <c>GlobalSection(ProjectConfigurationPlatforms)</c> would mean inventing a
/// <c>Debug|Any CPU</c> for projects whose real solution may define something else entirely, to be
/// read by nobody.
/// </para>
/// </remarks>
internal sealed class PartialSolution : IDisposable
{
    private const string CSharpProjectTypeGuid = "{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}";

    /// <summary>Absolute path of the generated solution file.</summary>
    public string Path { get; }

    /// <summary>
    /// The <c>Solution*</c> MSBuild properties, pointing at the <em>real</em> solution rather than
    /// at <see cref="Path"/>, so a project that reads <c>$(SolutionDir)</c> evaluates exactly as it
    /// would under a normal build.
    /// </summary>
    public IReadOnlyDictionary<string, string> GlobalProperties { get; }

    private PartialSolution(string path, IReadOnlyDictionary<string, string> globalProperties)
    {
        Path = path;
        GlobalProperties = globalProperties;
    }

    /// <summary>
    /// Writes a solution file listing <paramref name="projectPaths"/>, attributed to
    /// <paramref name="realSolutionPath"/> for the purposes of every solution-relative property.
    /// </summary>
    public static PartialSolution Create(string realSolutionPath, IReadOnlyCollection<string> projectPaths)
    {
        string dir = System.IO.Path.Combine(
            System.IO.Path.GetTempPath(), "roslyn-sense-partial", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);

        string path = System.IO.Path.Combine(
            dir, System.IO.Path.GetFileName(realSolutionPath));

        var text = new System.Text.StringBuilder();
        text.AppendLine("Microsoft Visual Studio Solution File, Format Version 12.00");
        text.AppendLine("# Generated by RoslynSense to batch-load a subset of " +
            System.IO.Path.GetFileName(realSolutionPath));

        foreach (string project in projectPaths)
        {
            // Absolute paths, because the generated file does not sit where the real one does and a
            // relative path would be resolved against the temp directory.
            text.AppendLine(
                $"Project(\"{CSharpProjectTypeGuid}\") = " +
                $"\"{System.IO.Path.GetFileNameWithoutExtension(project)}\", \"{project}\", " +
                $"\"{{{Guid.NewGuid().ToString().ToUpperInvariant()}}}\"");
            text.AppendLine("EndProject");
        }

        text.AppendLine("Global");
        text.AppendLine("EndGlobal");

        File.WriteAllText(path, text.ToString());

        string realDir = System.IO.Path.GetDirectoryName(realSolutionPath)!;
        var properties = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            // Trailing separator on SolutionDir: MSBuild's own definition has one, and
            // $(SolutionDir)src\Foo is how project files are written against it.
            ["SolutionDir"] = realDir.EndsWith(System.IO.Path.DirectorySeparatorChar)
                ? realDir
                : realDir + System.IO.Path.DirectorySeparatorChar,
            ["SolutionPath"] = realSolutionPath,
            ["SolutionFileName"] = System.IO.Path.GetFileName(realSolutionPath),
            ["SolutionName"] = System.IO.Path.GetFileNameWithoutExtension(realSolutionPath),
        };

        return new PartialSolution(path, properties);
    }

    public void Dispose()
    {
        try
        {
            string? dir = System.IO.Path.GetDirectoryName(Path);
            if (dir is not null && Directory.Exists(dir))
                Directory.Delete(dir, recursive: true);
        }
        catch
        {
            // A leftover temp file is not worth failing a load that has already succeeded; the
            // directory is under the OS temp root and gets reclaimed with everything else there.
        }
    }
}
