using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MediatorFixture.SourceGen;

/// <summary>
/// A stand-in for Zapto.Mediator's own generator, emitting the same shapes the real one does.
/// </summary>
/// <remarks>
/// A real generator rather than checked-in files, and deliberately unlike the protobuf fixture next
/// door. What is under test here is whether a reference search reaches into source-generated
/// documents at all — the whole Zapto half of the pack rests on it — so committing the output as
/// ordinary <c>.cs</c> would turn the assumption into a tautology.
/// </remarks>
[Generator]
public sealed class SenderExtensionsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var messages = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax { BaseList: not null },
                static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol is not null)
            .Select(static (symbol, _) => symbol!);

        context.RegisterSourceOutput(messages, static (ctx, symbol) => Emit(ctx, symbol));
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol type)
    {
        var request = type.AllInterfaces.FirstOrDefault(i =>
            i.ContainingNamespace?.ToDisplayString() == "MediatR" && i.Name == "IRequest" && i.Arity == 1);
        var notification = type.AllInterfaces.FirstOrDefault(i =>
            i.ContainingNamespace?.ToDisplayString() == "MediatR" && i.Name == "INotification");

        if (request is null && notification is null)
            return;

        string? ns = type.ContainingNamespace is { IsGlobalNamespace: false } containing
            ? containing.ToDisplayString()
            : null;

        string qualified = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string name = MethodName(type.Name, request is not null ? "Request" : "Notification");

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();

        if (ns is not null)
        {
            source.AppendLine($"namespace {ns}");
            source.AppendLine("{");
        }

        source.AppendLine("    public static partial class SenderExtensions");
        source.AppendLine("    {");

        if (request is not null)
        {
            string response = request.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            source.AppendLine($"        public static global::System.Threading.Tasks.ValueTask<{response}> {name}(this global::Zapto.Mediator.ISender sender, {qualified} request, global::System.Threading.CancellationToken cancellationToken = default)");
            source.AppendLine($"        => sender.Send<{qualified}, {response}>(request, cancellationToken);");

            if (ConstructorParameters(type) is { Length: > 0 } parameters)
            {
                string declarations = string.Join(", ", parameters.Select(p =>
                    $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name}"));
                string arguments = string.Join(", ", parameters.Select(p => p.Name));

                source.AppendLine();
                source.AppendLine($"        public static global::System.Threading.Tasks.ValueTask<{response}> {name}(this global::Zapto.Mediator.ISender sender, {declarations}, global::System.Threading.CancellationToken cancellationToken = default)");
                source.AppendLine($"        => sender.Send<{qualified}, {response}>(new {qualified}({arguments}), cancellationToken);");
            }
        }
        else
        {
            source.AppendLine($"        public static global::System.Threading.Tasks.ValueTask {name}(this global::Zapto.Mediator.IPublisher sender, {qualified} notification, global::System.Threading.CancellationToken cancellationToken = default)");
            source.AppendLine($"        => sender.Publish<{qualified}>(notification, cancellationToken);");
        }

        source.AppendLine("    }");

        if (ns is not null)
            source.AppendLine("}");

        string hint = (ns is null ? type.Name : $"{ns.Replace('.', '_')}_{type.Name}") + "_Extensions.g.cs";
        context.AddSource(hint, SourceText.From(source.ToString(), Encoding.UTF8));
    }

    /// <summary>The real generator's rule: strip the suffix the interface is named after, then
    /// append Async unless the wrapped method returns void.</summary>
    private static string MethodName(string typeName, string suffix)
    {
        string baseName = typeName.EndsWith(suffix, System.StringComparison.Ordinal)
            && typeName.Length != suffix.Length
            ? typeName.Substring(0, typeName.Length - suffix.Length)
            : typeName;

        return baseName + "Async";
    }

    private static IParameterSymbol[] ConstructorParameters(INamedTypeSymbol type) =>
        type.InstanceConstructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public && c.Parameters.Length > 0)
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault()
            ?.Parameters.ToArray() ?? [];
}
